openapi: 3.0.0
info:
  title: fhir-server-api
  version: 1.0.0
servers:
  - url: localhost://
paths:
  /fhir/r4/Patient:
    get:
      tags:
        - default
      summary: get
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /fhir/r4/Patient/{patientId}:
    get:
      tags:
        - default
      summary: "Find patient by ID"
      parameters:
        - name: "patientId"
          in: "path"
          description: "ID of patient"
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /fhir/r4/metadata:
    get:
      tags:
        - default
      summary: get
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}